checkpoint:
  path: "pretrained/weights.pth"
data:
  seed: 42
model:
  name: mesonet
  optimizer:
    lr: 0.0001
    weight_decay: 0.0001
  parameters:
    fc1_dim: 1024
    frontend_algorithm:
    - lfcc
    input_channels: 1
